# Generated by Django 5.2.6 on 2025-10-04 20:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the event (e.g., 'Beach Wedding', 'Mountain Hiking')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the event')),
                ('event_type', models.CharField(help_text="Type/category of event (e.g., 'wedding', 'outdoor_sports')", max_length=100)),
                ('location_name', models.CharField(help_text="Location name (e.g., 'Central Park, NYC')", max_length=200)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('target_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target_day', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('weather_sensitivity', models.JSONField(default=list, help_text="List of weather conditions this event is sensitive to (e.g., ['very_hot', 'very_wet'])")),
                ('last_analysis', models.JSONField(blank=True, help_text='Last compound extreme analysis results', null=True)),
                ('last_analysis_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
