name: Deploy to Azure App Service

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Django tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DEBUG: False
      run: |
        python manage.py test --settings=backend.settings
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

# Instructions to set up GitHub Secrets:
# 1. Go to your repository → Settings → Secrets and Variables → Actions
# 2. Add the following secrets:
#    - SECRET_KEY: Your Django secret key
#    - AZURE_WEBAPP_NAME: Your Azure App Service name
#    - AZURE_WEBAPP_PUBLISH_PROFILE: Download from Azure Portal → App Service → Get Publish Profile